steps:
  - label: ":java: Unit test with test services"
    agents:
      queue: "default"
      docker: "*"
    command: "./gradlew --no-daemon -Palpine=true test"
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky on"
    agents:
      queue: "default"
      docker: "*"
    command: "./gradlew --no-daemon -Palpine=true test"
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-on
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky off"
    agents:
      queue: "default"
      docker: "*"
    command: "./gradlew --no-daemon -Palpine=true test"
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-off
          config: docker/buildkite/docker-compose.yaml
  - wait