version: '3.5'

services:
  cassandra:
    image: cassandra:3.11
    logging:
      driver: none
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra

  statsd:
    image: hopsoft/graphite-statsd
    logging:
      driver: none
    ports:
      - "8080:80"
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
    networks:
      services-network:
        aliases:
          - statsd

  temporal:
    image: temporalio/temporal:last-thrift-release-auto-setup
    logging:
      driver: none
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
    depends_on:
      - cassandra
      - statsd
    networks:
      services-network:
        aliases:
          - temporal

  unit-test-docker-sticky-off:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    environment:
      - "USER=unittest"
      - "TEMPORAL_SEEDS=temporal"
      - "USE_DOCKER_SERVICE=true"
      - "STICKY_OFF=true"
    depends_on:
      - temporal
    volumes:
      - "../../:/temporal-java-client"
    networks:
      services-network:
        aliases:
          - unit-test-docker-sticky-off

  unit-test-docker-sticky-on:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    environment:
      - "USER=unittest"
      - "TEMPORAL_SEEDS=temporal"
      - "USE_DOCKER_SERVICE=true"
      - "STICKY_OFF=false"
    depends_on:
      - temporal
    volumes:
      - "../../:/temporal-java-client"
    networks:
      services-network:
        aliases:
          - unit-test-docker-sticky-on

  unit-test-test-service:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    environment:
      - "USER=unittest"
      - "USE_DOCKER_SERVICE=false"
    volumes:
      - "../../:/temporal-java-client"
    networks:
      services-network:
        aliases:
          - unit-test-test-service

networks:
  services-network:
    name: services-network
    driver: bridge